baseurl = "https://lilnate22.github.io/Crows-Nest"
languageCode = "en-us"
title = "Crows Nest"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

[params]
	# General information
	author = "lilnate22"
	description = "A material design theme for documentations."
	copyright = "Released under the GPLv3 license"

	# Repository
	provider = "GitHub"
	repo_url = "https://github.com/lilnate22/Crows-Nest"

	version = "1.0.0"
	logo = "images/logo.png"
	favicon = ""

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "blue"
    	accent  = "light-blue"

    [params.font]
    	text = "Ubuntu"
    	code = "Ubuntu Mono"


[social]
	twitter = ""
	github  = "lilnate22"
	email   = ""


[[menu.main]]
	name   = "Introduction"
	url    = "/"
	weight = 9

[[menu.main]]
	name   = "Getting started"
	url    = "getting-started/"
	weight = 10

[[menu.main]]
	name   = "License"
	url    = "license/"
	weight = 11


[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
